spring:
    application:
        name: api-gateway

    data:
        mongodb:
            uri: ${MONGO_URI}

server:
    port: ${GATEWAY_SERVICE_PORT}

hungrycoder:
    app:
        jwtSecret: "======================BezKoder=Spring==========================="
        jwtExpirationMs: 86400000
